import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import pickle

class SeverityClassifier:
    """
    Inductive Learning / Decision Tree for classifying incident severity.
    Syllabus Module IX
    """
    def __init__(self):
        self.model = DecisionTreeClassifier(criterion='entropy', max_depth=5)
        self.is_trained = False
        self.feature_names = ['incident_type', 'affected_population', 'structural_damage', 'weather_condition']

    def generate_simulated_dataset(self, n_samples=1000):
        """Generates simulated data for training if real datasets are unavailable."""
        np.random.seed(42)
        
        # Features:
        # incident_type: 0 (Medical), 1 (Fire), 2 (Flood)
        # affected_population: 0 to 1000
        # structural_damage: 0 (None), 1 (Minor), 2 (Severe)
        # weather_condition: 0 (Clear), 1 (Rain), 2 (Storm)
        
        X = {
            'incident_type': np.random.randint(0, 3, n_samples),
            'affected_population': np.random.randint(0, 1000, n_samples),
            'structural_damage': np.random.randint(0, 3, n_samples),
            'weather_condition': np.random.randint(0, 3, n_samples)
        }
        
        df = pd.DataFrame(X)
        
        # Rule for labels (0: Low, 1: Medium, 2: High)
        y = []
        for i, row in df.iterrows():
            score = row['affected_population'] / 1000.0 + (row['structural_damage'] / 2.0) + (row['weather_condition'] / 4.0)
            if row['incident_type'] == 1: score += 0.5 # Fire inherently riskier in this simulation
            
            if score > 1.5:
                y.append(2) # High
            elif score > 0.8:
                y.append(1) # Medium
            else:
                y.append(0) # Low
                
        df['severity_label'] = y
        return df

    def train(self, dataset):
        """Trains the Decision Tree on the dataset."""
        X = dataset[self.feature_names]
        y = dataset['severity_label']
        
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        self.model.fit(X_train, y_train)
        self.is_trained = True
        
        # Evaluate
        predictions = self.model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        report = classification_report(y_test, predictions)
        
        return {
            'accuracy': accuracy,
            'report': report
        }

    def predict(self, features_dict):
        """Predicts severity given feature dictionary."""
        if not self.is_trained:
            raise Exception("Model is not trained yet.")
            
        df = pd.DataFrame([features_dict])
        prediction = self.model.predict(df)[0]
        
        labels = {0: 'Low', 1: 'Medium', 2: 'High'}
        
        return {
            'predicted_severity': labels[prediction],
            'confidence_note': 'Prediction generated by Decision Tree. Requires human validation.'
        }


if __name__ == "__main__":
    classifier = SeverityClassifier()
    print("Generating simulated dataset...")
    dataset = classifier.generate_simulated_dataset()
    
    print("Training Model...")
    eval_results = classifier.train(dataset)
    print(f"Model Accuracy: {eval_results['accuracy']:.2f}")
    
    # Test Prediction
    test_incident = {
        'incident_type': 1, # Fire
        'affected_population': 500,
        'structural_damage': 2, # Severe
        'weather_condition': 1  # Rain
    }
    
    pred = classifier.predict(test_incident)
    print(f"Prediction for test incident: {pred}")
